apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tayo-eks-cluster
  region: us-west-1

nodeGroups:
  - name: worker-1
    instanceType: t3.large
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: m5.xlarge
  #   desiredCapacity: 2
  #   volumeSize: 100
  #   ssh:
  #     publicKeyPath: ~/.ssh/ec2_id_rsa.pub


