controller:
  componentName: "jenkins-controller"
  image:
    repository: "jenkins/jenkins"
    tag:
    tagLabel: jdk17
    pullPolicy: "Always"
    
  ingress:
    enabled: true 
    apiVersion: "extensions/v1beta1"
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostName: jenkins.thesausage.online
    tls: 
    - secretName: jenkins.thesausage.online
      hosts:
        - jenkins.thesausage.online
  installPlugins:
    - kubernetes:4253.v7700d91739e5
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.2.2
    - configuration-as-code:1810.v9b_c30a_249a_4c
  additionalPlugins: 
    - blueocean:1.25.5
    - credentials-binding:1.24
    - git-changelog:3.0
    - git-client:3.6.0
    - git-server:1.9
  additionalExistingSecrets: 
   - name: github
     keyName: github_token
  JCasC:
    defaultConfig: true
    configScripts: 
      welcome-message: |
        jenkins:
          systemMessage: Welcome to temitayo's CI\CD server. This Jenkins is configured and managed 'as code'.
      pipeline: |
        jobs:
          - script: >
              folder('tayo') {
                displayName('tayo')
                description('Contains tayo's Jenkins Pipelines')
              }
          - script: >
              multibranchPipelineJob('tayo/tooling-app') {
                branchSources {
                  git {
                    remote('https://github.com/temitayo-ob/tooling.git')
                    credentialsId('github')
                    id('tooling-app')
                  }
                }
              }
      security-config: |
        credentials:
            system:
              domainCredentials:
              - credentials:
                - usernamePassword:
                    id: github
                    username: temitayo-ob
                    password: ${github-github_token}
                    scope: GLOBAL
                    description: Github
    


